name: ksch_dart_client
description: Abstraction of the API of the K.S.C.H. Workflows backend

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  uuid: ^3.0.4
  http: ^0.13.3

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.14.4
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
