name: ksch_dart_client
description: Abstraction of the API of the K.S.C.H. Workflows backend

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.3
  dart_jsonwebtoken: ^2.4.1
  effective_dart: ^1.3.1
  json_serializable: ^4.1.2
  test: ^1.14.4

